const vocabulary = [
  // Add more vocabulary entries here with or without a group
  {
    group: "Basic Communication & Greetings",
    emoji: ["🟩"],
    chinese: "妈",
    pinyin: "mā",
    english: "High level tone",
    romanian: "ton înalt",
    german: "fest",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["🟦"],
    chinese: "麻",
    pinyin: "má",
    english: "Rising tone",
    romanian: "ton ascendent",
    german: "? (question-like tone)",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["🟨"],
    chinese: "马",
    pinyin: "mǎ",
    english: "Falling-rising tone",
    romanian: "ton căzut-ridicat",
    german: "deep and longer",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["🟥"],
    chinese: "骂",
    pinyin: "mà",
    english: "Falling tone",
    romanian: "ton căzut",
    german: "abrupt",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["👋"],
    chinese: "你好",
    pinyin: "nǐ hǎo!",
    english: "Hello",
    romanian: "Salut",
    german: "Guten Morgen, Tag, Abend...",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["🤔"],
    chinese: "你好吗?",
    pinyin: "nǐ hǎo ma?",
    english: "How are you?",
    romanian: "Cum ești?",
    german: "Wie geht es dir?",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["😊"],
    chinese: "我很好!",
    pinyin: "wǒ hěn hǎo!",
    english: "I am good!",
    romanian: "Sunt bine!",
    german: "Mir geht es gut!",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["🙏"],
    chinese: "谢谢",
    pinyin: "xiè xiè!",
    english: "Thank you",
    romanian: "Mulțumesc",
    german: "Danke",
  },
  {
    group: "Basic Communication & Greetings",
    emoji: ["👋"],
    chinese: "再见",
    pinyin: "zài jiàn!",
    english: "Goodbye",
    romanian: "La revedere",
    german: "Auf Wiedersehen",
  },
  {
    group: "Personal Pronouns",
    emoji: ["🫵"],
    chinese: "你",
    pinyin: "nǐ",
    english: "You (informal)",
    romanian: "tu",
    german: "du",
  },
  {
    group: "Personal Pronouns",
    emoji: ["🫴"],
    chinese: "您",
    pinyin: "nín",
    english: "You (formal)",
    romanian: "dumneavoastră",
    german: "Sie",
  },
  {
    group: "Personal Pronouns",
    emoji: ["🫀", "👤"],
    chinese: "我",
    pinyin: "wǒ",
    english: "I",
    romanian: "eu",
    german: "ich",
  },
  {
    group: "Personal Pronouns",
    emoji: ["🧍‍♂️", "🧍‍♀️", "🐾"],
    chinese: "他/她/它",
    pinyin: "tā",
    english: "He / She / It",
    romanian: "el / ea",
    german: "er / sie / es",
  },
  {
    group: "Personal Pronouns",
    emoji: ["👥", "👨‍👩‍👧‍👦"],
    chinese: "我们",
    pinyin: "wǒ men",
    english: "We",
    romanian: "noi",
    german: "wir",
  },
  {
    group: "Personal Pronouns",
    emoji: ["👥", "👨‍👩‍👧‍👦"],
    chinese: "你们",
    pinyin: "nǐ men",
    english: "You all",
    romanian: "void",
    german: "ihr",
  },
  {
    group: "Personal Pronouns",
    emoji: ["👫", "👫", "👨‍👩‍👧‍👦"],
    chinese: "他们/她们/它们",
    pinyin: "tā men",
    english: "They",
    romanian: "ei / ele",
    german: "sie",
  },
  {
    group: "Professions",
    emoji: ["🏢", "👔"],
    chinese: "职业",
    pinyin: "zhíyè",
    english: "Profession",
    romanian: "Profesiune",
    german: "Beruf",
  },
  {
    group: "Professions",
    emoji: ["🧑‍💼", "💼"],
    chinese: "经理",
    pinyin: "jīnglǐ",
    english: "Manager",
    romanian: "Manager",
    german: "Manager",
  },
  {
    group: "Professions",
    emoji: ["🧑‍⚕️", "🧑‍🤝‍🧑"],
    chinese: "护理员",
    pinyin: "hùlǐ yuán",
    english: "Caregiver",
    romanian: "Îngrijitor",
    german: "Betreuer",
  },
  {
    group: "Professions",
    emoji: ["🧑‍🍳", "🍽️"],
    chinese: "服务员",
    pinyin: "fúwùyuán",
    english: "Waiter",
    romanian: "Chelner",
    german: "Kellner",
  },
  {
    group: "Professions",
    emoji: ["🛠️", "👷"],
    chinese: "工程师",
    pinyin: "gōngchéngshī",
    english: "Engineer",
    romanian: "Inginer",
    german: "Ingenieur",
  },
  {
    group: "Professions",
    emoji: ["💻", "🖥️"],
    chinese: "电脑工程师",
    pinyin: "diànnǎo gōngchéngshī",
    english: "Computer Engineer",
    romanian: "Inginer de calculatoare",
    german: "Computeringenieur",
  },
  {
    group: "Professions",
    emoji: ["🩺", "👨‍⚕️"],
    chinese: "医生",
    pinyin: "yīshēng",
    english: "Doctor",
    romanian: "Doctor",
    german: "Arzt",
  },
  {
    group: "Professions",
    emoji: ["🗂️", "🖊️"],
    chinese: "秘书",
    pinyin: "mìshū",
    english: "Secretary",
    romanian: "Secretar",
    german: "Sekretär",
  },
  {
    group: "Professions",
    emoji: ["🎓", "📚"],
    chinese: "学生",
    pinyin: "xuéshēng",
    english: "Student",
    romanian: "Student",
    german: "Student",
  },
  {
    group: "Professions",
    emoji: ["🛍️", "💰"],
    chinese: "售货员",
    pinyin: "shòuhuòyuán",
    english: "Salesperson",
    romanian: "Vânzător",
    german: "Verkäufer",
  },
  {
    group: "Common Phrases",
    emoji: ["🤨"],
    chinese: "你叫什么名字?",
    pinyin: "Nǐ jiào shénme míngzì?",
    english: "What is your name?",
    romanian: "Cum te numești?",
    german: "Wie heißt du?",
  },
  {
    group: "Common Phrases",
    emoji: ["🧑"],
    chinese: "我叫王伟",
    pinyin: "Wǒ jiào Wáng Wěi",
    english: "My name is Wang Wei.",
    romanian: "Mă numesc Wang Wei.",
    german: "Mein Name ist Wang Wei.",
  },
  {
    group: "Common Phrases",
    emoji: ["🤵"],
    chinese: "您贵姓?",
    pinyin: "Nín guì xìng?",
    english: "What is your surname? (polite)",
    romanian: "Care este numele dumneavoastră?",
    german: "Wie ist Ihr Nachname?",
  },
  {
    group: "Common Phrases",
    emoji: ["🏷️"],
    chinese: "我姓王",
    pinyin: "Wǒ xìng Wáng",
    english: "My surname is Wang.",
    romanian: "Mă numesc Wang.",
    german: "Mein Nachname ist Wang.",
  },
  {
    group: "Common Vocabulary",
    emoji: ["🤷‍♂️"],
    chinese: "马马虎虎",
    pinyin: "mǎmǎ hūhū",
    english: "Not so good",
    romanian: "așa și așa",
    german: "so la la",
  },
  {
    group: "Common Phrases",
    emoji: ["❣️"],
    chinese: "你爱我吗?",
    pinyin: "nǐ ài wǒ ma?",
    english: "Do you love me?",
    romanian: "Mă iubești?",
    german: "Liebst du mich?",
  },
  {
    group: "Common Phrases",
    emoji: ["🍲"],
    chinese: "我饿",
    pinyin: "wǒ è",
    english: "I am hungry",
    romanian: "Sunt înfometat",
    german: "Ich bin hungrig",
  },
  {
    group: "Common Phrases",
    emoji: ["💻"],
    chinese: "你也忙吗?",
    pinyin: "nǐ yě máng ma?",
    english: "Are you also busy?",
    romanian: "Ești și tu ocupat?",
    german: "Bist du auch beschäftigt?",
  },
  {
    group: "Common Vocabulary",
    emoji: ["🐣"],
    chinese: "小",
    pinyin: "xiǎo",
    english: "Small",
    romanian: "Mic",
    german: "Herzradikal",
  },
  {
    group: "Common Vocabulary",
    emoji: ["👁️"],
    chinese: "目",
    pinyin: "mù",
    english: "Eye",
    romanian: "Ochi",
    german: "Auge",
  },
  {
    group: "Common Vocabulary",
    emoji: ["👨"],
    chinese: "男",
    pinyin: "nán",
    english: "Male",
    romanian: "Bărbat",
    german: "Mann",
  },
  {
    group: "Common Vocabulary",
    emoji: ["👩"],
    chinese: "女",
    pinyin: "nǚ",
    english: "Female",
    romanian: "Femeie",
    german: "Frau",
  },
  {
    group: "Common Vocabulary",
    emoji: ["🌟"],
    chinese: "很",
    pinyin: "hěn",
    english: "Very",
    romanian: "foarte",
    german: "sehr",
  },
  {
    group: "Common Vocabulary",
    emoji: ["➕"],
    chinese: "也",
    pinyin: "yě",
    english: "Also",
    romanian: "de asemenea",
    german: "auch",
  },
  {
    group: "Common Vocabulary",
    emoji: ["❓"],
    chinese: "吗",
    pinyin: "ma",
    english: "Question particle",
    romanian: "particulă de întrebare",
    german: "Fragepartikel",
  },
  {
    group: "Common Vocabulary",
    emoji: ["🔄"],
    chinese: "呢",
    pinyin: "ne",
    english: "Question particle for follow-up questions",
    romanian: "particulă de întrebare",
    german: "Fragepartikel",
  },
  {
    group: "Common Vocabulary",
    emoji: ["😫"],
    chinese: "累",
    pinyin: "lěi",
    english: "Tired",
    romanian: "obosit",
    german: "müde",
  },
  {
    group: "Common Vocabulary",
    emoji: ["📆"],
    chinese: "忙",
    pinyin: "máng",
    english: "Busy",
    romanian: "ocupat",
    german: "beschäftigt",
  },
  {
    group: "Common Vocabulary",
    emoji: ["🍲"],
    chinese: "饿",
    pinyin: "è",
    english: "Hungry",
    romanian: "înfometat",
    german: "hungrig",
  },
  {
    group: "Common Vocabulary",
    emoji: ["💦"],
    chinese: "渴",
    pinyin: "kě",
    english: "Thirsty",
    romanian: "însetat",
    german: "durstig",
  },
  {
    group: "Common Vocabulary",
    emoji: ["❤️"],
    chinese: "爱",
    pinyin: "ài",
    english: "To love",
    romanian: "a iubi",
    german: "lieben",
  },
  {
    group: "Common Vocabulary",
    emoji: ["👍"],
    chinese: "是",
    pinyin: "shì",
    english: "Yes / To be",
    romanian: "da",
    german: "sein",
  },
  {
    group: "Common Vocabulary",
    emoji: ["👎"],
    chinese: "不",
    pinyin: "bù",
    english: "No",
    romanian: "nu",
    german: "nein",
  },
  {
    group: "Common Vocabulary",
    emoji: ["💧"],
    chinese: "水",
    pinyin: "shuǐ",
    english: "Water",
    romanian: "apă",
    german: "Wasser",
  },
  {
    group: "Introduce Yourself",
    emoji: ["👋"],
    chinese: "你好",
    pinyin: "nǐ hǎo",
    english: "Hello",
    romanian: "Salut",
    german: "Hallo",
  },
  {
    group: "Introduce Yourself",
    emoji: ["🙂"],
    chinese: "请问，你叫什么名字？",
    pinyin: "qǐng wèn, nǐ jiào shénme míngzi?",
    english: "May I ask, what's your name?",
    romanian: "Îmi puteți spune, cum te numești?",
    german: "Darf ich fragen, wie heißt du?",
  },
  {
    group: "Introduce Yourself",
    emoji: ["🙇‍♂️"],
    chinese: "您贵姓？",
    pinyin: "nín guì xìng?",
    english: "What is your honorable surname?",
    romanian: "Care este numele dvs. onorabil?",
    german: "Wie lautet Ihr ehrenwerter Nachname?",
  },
  {
    group: "Introduce Yourself",
    emoji: ["👨"],
    chinese: "我姓李，我叫李丽。",
    pinyin: "wǒ xìng Lǐ, wǒ jiào Lǐ Lì.",
    english: "My surname is Li, and my name is Li Li.",
    romanian: "Numele meu de familie este Li, mă numesc Li Li.",
    german: "Mein Nachname ist Li, ich heiße Li Li.",
  },
  {
    group: "Introduce Yourself",
    emoji: ["🙂"],
    chinese: "您呢？",
    pinyin: "nín ne?",
    english: "And you?",
    romanian: "Dar dvs.?",
    german: "Und Sie?",
  },
  {
    group: "Introduce Yourself",
    emoji: ["🙂"],
    chinese: "我姓Doe，我叫Doe John。",
    pinyin: "wǒ xìng Doe, wǒ jiào Doe John.",
    english: "My surname is Doe, and my name is Doe John.",
    romanian: "Numele meu de familie este Doe, mă numesc Doe John.",
    german: "Mein Nachname ist Doe, ich heiße Doe John.",
  },
  {
    group: "Introduce Yourself",
    emoji: ["😊"],
    chinese: "我很高兴认识您。",
    pinyin: "wǒ hěn gāoxìng rènshi nǐn.",
    english: "I am very happy to meet you.",
    romanian: "Mă bucur foarte mult să vă cunosc.",
    german: "Es freut mich sehr, Sie kennenzulernen.",
  },
  {
    group: "Introduce Yourself",
    emoji: ["😊"],
    chinese: "我也很高兴认识您。",
    pinyin: "wǒ yě hěn gāoxìng rènshi nǐn.",
    english: "I am also very happy to meet you.",
    romanian: "Mă bucur și eu foarte mult să vă cunosc.",
    german: "Es freut mich auch sehr, Sie kennenzulernen.",
  },
  {
    group: "Introduce Yourself",
    emoji: ["🙏"],
    chinese: "谢谢，再见。",
    pinyin: "xièxiè, zàijiàn.",
    english: "Thank you, goodbye.",
    romanian: "Mulțumesc, la revedere.",
    german: "Danke, auf Wiedersehen.",
  },
  {
    group: "Introduce Yourself",
    emoji: ["👋"],
    chinese: "再见。",
    pinyin: "zàijiàn.",
    english: "Goodbye.",
    romanian: "La revedere.",
    german: "Auf Wiedersehen.",
  },
  {
    group: "Introduce Someone Else",
    emoji: ["🤝"],
    chinese: "请问，他叫什么名字？",
    pinyin: "qǐng wèn, tā jiào shénme míngzi?",
    english: "May I ask, what's their name?",
    romanian: "Îmi puteți spune, cum se numește?",
    german: "Darf ich fragen, wie heißt er/sie?",
  },
  {
    group: "Introduce Someone Else",
    emoji: ["🙂"],
    chinese: "我介绍一下，他姓李，他叫李丽，他是我的朋友。",
    pinyin:
      "wǒ jièshào yíxià, tā xìng Lǐ, tā jiào Lǐ Lì, tā shì wǒ de péngyou.",
    english:
      "Let me introduce them. Their surname is Li, and their name is Li Li. They are my friend.",
    romanian:
      "Permiteți-mi să-l prezint. Numele său de familie este Li, iar numele său este Li Li. Este prietenul meu.",
    german:
      "Lassen Sie mich sie vorstellen. Ihr Nachname ist Li, sie heißt Li Li. Sie ist meine Freundin.",
  },
  {
    group: "Introduce Someone Else",
    emoji: ["🙂"],
    chinese: "你好，你姓李，叫李丽，对吗？",
    pinyin: "nǐ hǎo, nǐ xìng Lǐ, jiào Lǐ Lì, duì ma?",
    english: "Hello, your surname is Li, and your name is Li Li, right?",
    romanian:
      "Salut, numele tău de familie este Li și te numești Li Li, corect?",
    german: "Hallo, dein Nachname ist Li, und du heißt Li Li, richtig?",
  },
  {
    group: "Introduce Someone Else",
    emoji: ["😊"],
    chinese: "我也很高兴认识您，再见。",
    pinyin: "wǒ yě hěn gāoxìng rènshi nǐn, zàijiàn.",
    english: "I am also happy to meet you, goodbye.",
    romanian: "Mă bucur și eu să vă cunosc, la revedere.",
    german: "Es freut mich auch, Sie kennenzulernen, auf Wiedersehen.",
  },
  {
    group: "Ask About Career",
    emoji: ["👩‍🏫"],
    chinese: "请问，您是老师吗？",
    pinyin: "qǐng wèn, nín shì lǎoshī ma?",
    english: "May I ask, are you a teacher?",
    romanian: "Îmi permiteți să întreb, sunteți profesor?",
    german: "Darf ich fragen, sind Sie Lehrer/Lehrerin?",
  },
  {
    group: "Ask About Career",
    emoji: ["👨‍💻"],
    chinese: "不是，我不是老师。我是电脑工程师，他是老师。",
    pinyin:
      "Bú shì, wǒ bú shì lǎoshī. wǒ shì diànnǎo gōngchéngshī, tā shì lǎoshī.",
    english:
      "No, I’m not a teacher. I’m a computer engineer, they are a teacher.",
    romanian:
      "Nu, nu sunt profesor. Sunt inginer de calculatoare, el/ea este profesor.",
    german:
      "Nein, ich bin kein Lehrer. Ich bin Computer-Ingenieur, er/sie ist Lehrer/in.",
  },
  {
    group: "Ask About Career",
    emoji: ["👩‍🏫"],
    chinese: "是，我是老师，你们呢？你们干什么工作？",
    pinyin: "shì, wǒ shì lǎoshī, nǐmen ne? nǐmen gàn shénme gōngzuò?",
    english: "Yes, I am a teacher, and you? What do you do?",
    romanian: "Da, sunt profesor, dar voi? Ce faceți?",
    german: "Ja, ich bin Lehrer/in, und ihr? Was macht ihr?",
  },
  {
    group: "Ask About Career",
    emoji: ["👩‍💼"],
    chinese: "我是秘书。",
    pinyin: "wǒ shì mìshū.",
    english: "I’m a secretary.",
    romanian: "Sunt secretară.",
    german: "Ich bin Sekretärin.",
  },
  {
    group: "Ask About Career",
    emoji: ["🎓"],
    chinese: "我是学生。",
    pinyin: "wǒ shì xuéshēng.",
    english: "I’m a student.",
    romanian: "Sunt student.",
    german: "Ich bin Student.",
  },
  {
    group: "Ask About Career",
    emoji: ["💼"],
    chinese: "这是我的名片。",
    pinyin: "Zhè shì wǒ de míngpiàn.",
    english: "This is my business card.",
    romanian: "Aceasta este cartea mea de vizită.",
    german: "Das ist meine Visitenkarte.",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇨🇳"],
    chinese: "中国",
    pinyin: "Zhōngguó",
    english: "China",
    romanian: "China",
    german: "China",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🏯"],
    chinese: "汉语",
    pinyin: "Hàn yǔ",
    english: "Mandarin",
    romanian: "Limba chineză",
    german: "Hauptsprache",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇬🇧"],
    chinese: "英国",
    pinyin: "Yīngguó",
    english: "England",
    romanian: "Anglia",
    german: "England",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇫🇷"],
    chinese: "法国",
    pinyin: "Fàguó",
    english: "France",
    romanian: "Franța",
    german: "Frankreich",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇪🇸"],
    chinese: "西班牙",
    pinyin: "Xībānyá",
    english: "Spain",
    romanian: "Spania",
    german: "Spanien",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇮🇹"],
    chinese: "意大利",
    pinyin: "Yìdàlì",
    english: "Italy",
    romanian: "Italia",
    german: "Italien",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇩🇪"],
    chinese: "德国",
    pinyin: "Déguó",
    english: "Germany",
    romanian: "Germania",
    german: "Deutschland",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇺🇸"],
    chinese: "美国",
    pinyin: "Měiguó",
    english: "USA",
    romanian: "Statele Unite",
    german: "USA",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇯🇵"],
    chinese: "日本",
    pinyin: "Rìběn",
    english: "Japan",
    romanian: "Japonia",
    german: "Japan",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇦🇹"],
    chinese: "奥地利",
    pinyin: "Àodìlì",
    english: "Austria",
    romanian: "Austria",
    german: "Österreich",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇨🇭"],
    chinese: "瑞士",
    pinyin: "Ruìshì",
    english: "Switzerland",
    romanian: "Elveția",
    german: "Schweiz",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🌍"],
    chinese: "国家",
    pinyin: "guójiā",
    english: "Country",
    romanian: "Țară",
    german: "Land",
  },
  {
    group: "Common Vocabulary",
    emoji: ["📍"],
    chinese: "在",
    pinyin: "zài",
    english: "to be (in, on, at)",
    romanian: "a fi (în, pe, la)",
    german: "sich befinden (in, bei, an, auf)",
  },
  {
    group: "Common Vocabulary",
    emoji: ["📍"],
    chinese: "这儿",
    pinyin: "zhèr",
    english: "here",
    romanian: "aici",
    german: "hier",
  },
  {
    group: "Common Vocabulary",
    emoji: ["📍"],
    chinese: "哪儿",
    pinyin: "nǎr",
    english: "where",
    romanian: "unde",
    german: "wo",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🍲"],
    chinese: "菜",
    pinyin: "cài",
    english: "dish (food)",
    romanian: "fel de mâncare",
    german: "Gericht",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🍽️"],
    chinese: "饭",
    pinyin: "fàn",
    english: "food",
    romanian: "mâncare",
    german: "Essen",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🍽️"],
    chinese: "英国菜",
    pinyin: "Yīngguó cài",
    english: "English food",
    romanian: "Mâncare englezească",
    german: "englisches Essen",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🗣️"],
    chinese: "你是哪个国家人？",
    pinyin: "nǐ shì nǎge guójiā rén?",
    english: "Which country are you from?",
    romanian: "Din ce țară ești?",
    german: "Aus welchem Land kommst du?",
  },
  {
    group: "Countries, Languages, and Food",
    emoji: ["🇷🇴"],
    chinese: "罗马尼亚",
    pinyin: "Luómǎníyà",
    english: "Romania",
    romanian: "România",
    german: "Rumänien",
  },
  // Add more vocabulary entries here
];

function displayVocabulary() {
  const vocabList = document.getElementById("vocabulary-list");
  const groups = {};

  // Group vocabulary items
  vocabulary.forEach((item) => {
    const group = item.group || "Ungrouped";
    if (!groups[group]) {
      groups[group] = [];
    }
    groups[group].push(item);
  });

  // Display grouped vocabulary
  Object.keys(groups).forEach((groupName, index) => {
    // Create a section for each group
    const groupSection = document.createElement("div");
    groupSection.classList.add("group-section");

    const groupHeader = document.createElement("h2");
    groupHeader.classList.add("group-header");

    // Set the initial arrow based on whether the group is open or closed
    groupHeader.textContent = `${groupName} ${index === 0 ? "▼" : "►"}`;

    // Add toggle functionality to the header
    groupHeader.addEventListener("click", () => {
      const isOpen = groupHeader.textContent.includes("▼");
      groupHeader.textContent = `${groupName} ${isOpen ? "►" : "▼"}`;

      const vocabItems = groupSection.querySelectorAll(".vocab-item");
      vocabItems.forEach((item) => {
        item.classList.toggle("hidden");
      });
    });

    groupSection.appendChild(groupHeader);

    // Iterate over vocabulary items in the group
    groups[groupName].forEach((item) => {
      const vocabItem = document.createElement("div");
      vocabItem.classList.add("vocab-item");

      // Initial visibility setting: Show items in the first group, hide others
      if (index !== 0) vocabItem.classList.add("hidden");

      const emojiHTML = item.emoji
        .map((e) => `<span class="emoji">${e}</span>`)
        .join("");

      vocabItem.innerHTML = `
      <div class="vocab-content">
        <div class="speaker-icon">🔊</div>
        <div class="chinese">
          ${emojiHTML}
          <span class="chinese-character">${item.chinese}</span>
          <span class="pinyin">${item.pinyin}</span>
        </div>
        <div class="translations">
          <div class="translation translation-english">${item.english}</div>
          <div class="translation translation-romanian">${item.romanian}</div>
          <div class="translation translation-german">${item.german}</div>
        </div>
      </div>
    `;
      groupSection.appendChild(vocabItem);
    });

    vocabList.appendChild(groupSection);
  });
}

// Call function to display the vocabulary on page load
window.onload = displayVocabulary;
